import { ThemeDefinition } from '@/lib/types';

export const retroTheme: ThemeDefinition = {
  id: 'retro',
  label: "retro '90s",
  shortLabel: 'retro',
  isNew: true,
  description: 'authentic windows 95 desktop experience with classic system colors.',
  fontFamily: '"MS Sans Serif", "Tahoma", "Verdana", sans-serif',
  mode: 'light',
  category: 'soft',
  preview: ['#000080', '#c0c0c0', '#ffffff'],
  colors: {
    background: '#c0c0c0',
    backgroundAlt: '#c0c0c0',
    surface: '#c0c0c0',
    surfaceSoft: '#d4d0c8',
    surfaceElevated: '#d4d0c8',
    surfaceHighlight: '#ffffff',
    primary: '#000080',
    primarySoft: '#0a246a',
    secondary: '#808080',
    accent: '#0000ee',
    text: '#000000',
    textMuted: '#404040',
    textSubtle: '#404040',
    textInverse: '#ffffff',
    success: '#008000',
    warning: '#ffcc00',
    error: '#cc0000',
    border: '#808080',
    borderStrong: '#404040',
  },
  glow: {
    primary: 'none',
    secondary: 'none',
    accent: 'none',
    focus: '0 0 0 1px #000000 dotted',
  },
  radius: {
    sm: '0px',
    md: '0px',
    lg: '0px',
    xl: '0px',
    pill: '0px',
  },
  elevation: {
    soft: 'none',
    card: 'none',
    strong: 'none',
    floating: 'none',
    nav: 'none',
  },
  effects: {
    pageGradient: 'none',
    surfaceGradient: 'none',
    heroGradient: 'none',
  },
  motion: {
    id: 'retro-static',
    page: { distance: 0, scale: 1, blur: 0, fadeDuration: 0.01, spring: { stiffness: 1000, damping: 100, mass: 1 } },
    swipe: { threshold: 50, velocityThreshold: 0.5, distance: 0, scale: 1, fadeDuration: 0.01, spring: { stiffness: 1000, damping: 100, mass: 1 } },
    reveal: { y: 0, blur: 0, scale: 1, stagger: 0, delay: 0, duration: 0.01, ease: [0, 0, 1, 1] },
    micro: { tapScale: 1, hoverScale: 1, hoverY: 0, duration: 0.01 },
    route: { panelTravel: 0, panelScale: 1, panelOpacity: 1, duration: 0.01, labelDuration: 0.01 },
    intro: { logoScale: 1, glowScale: 1, duration: 0.01, delay: 0 },
  },
};
